### ISSUE TITLE
add enjarify

### ISSUE THREAD

**Issue by anp** [anp/lolbench#38]
https://github.com/Storyyeller/enjarify/tree/go/enjarify-rs

**Comment by jhwgh1968** [comment]
I looked into this a bit, and apparently there are not tests for the Rust rewrite. That's because it does not compile at all -- not even on Rust 1.36!

@anp, could you clarify what benchmarks you are referring to with this issue?

EDIT: It seems there is test code, it is just not in `#[test]` blocks. However, the inability to compile is still a problem. Are they still useful?

**Comment by jhwgh1968** [comment]
The compiler error, for the record:
```
   Compiling rustc-serialize v0.3.19
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^
```

**Comment by anp** [comment]
Alas! Thanks for looking into it. IIRC, this was originally referring to https://medium.com/@robertgrosse/parallelizing-enjarify-in-go-and-rust-21055d64af7e and some related posts about comparing the rewrites.
